### PR TITLE
Add new VSD file

### PR DESCRIPTION
**Pull request by klk32003**

### CODE REVIEW

**Comment by rhwood** [comment]
This is class 64 from which country/railroad/era?

**Comment by klk32003** [comment]
It's a class 94 (not class 64) from Germany, DB BR 94 ([Deutsche Bundesbahn, Baureihe 94](https://en.wikipedia.org/wiki/Prussian_T_16.1)).

edited: reference to English text instead of a German text

**Comment by rhwood** [comment]
@klk32003 Thank you.

**Comment by klk32003** [comment]
@rhwood Thank you for merging.

**Pull request merged**
